development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_app_development
  pool: 5
  username: root
  password: 

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_app_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_app_production
  pool: 5
  username: root
  password: 

cucumber:
  <<: *test
